name: release

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - name: Install Archlinux
        run: curl -L https://github.com/zaoqi/github-actions-archlinux/raw/master/install.sh | sh

      - name: Build image
        run: |
          sudo pacman -S archiso
          mkarchiso -v -w work -o out .
